/**
 * Client helpers for generating and listing QuickBooks exports.
 *
 * The actual CSV is generated by the `exportCommissionsCsv` Cloud
 * Function. This module just calls the function and reads the
 * `quickBooksExports/{exportId}` receipt docs it writes.
 */
import {
  collection,
  onSnapshot,
  orderBy,
  query,
  limit as limitQ,
} from "firebase/firestore";
import { httpsCallable } from "firebase/functions";
import { firebaseDb, firebaseFunctions } from "../firebase";
import type { QuickBooksExportDoc } from "../types/commission";

const exportsCol = (companyId: string) =>
  collection(firebaseDb, "companies", companyId, "quickBooksExports");

export interface GenerateExportInput {
  companyId: string;
  /** ISO date inclusive. */
  periodStart: string;
  periodEnd: string;
  includeExportedPayments?: boolean;
}

export interface GenerateExportResult {
  exportId: string;
  downloadUrl: string;
  paymentsFileName: string;
  commissionsFileName: string;
  paymentCount: number;
  totalCommissionAmount: number;
}

/**
 * Invoke the `exportCommissionsCsv` callable. Returns the signed download
 * URL the browser can hit directly to save the zipped CSVs.
 */
export async function generateCommissionsExport(
  input: GenerateExportInput
): Promise<GenerateExportResult> {
  const fn = httpsCallable<GenerateExportInput, GenerateExportResult>(
    firebaseFunctions,
    "exportCommissionsCsv"
  );
  const res = await fn(input);
  return res.data;
}

export function subscribeExports(
  companyId: string,
  onData: (rows: QuickBooksExportDoc[]) => void,
  onError?: (e: Error) => void
): () => void {
  const q = query(
    exportsCol(companyId),
    orderBy("createdAt", "desc"),
    limitQ(100)
  );
  return onSnapshot(
    q,
    (snap) => {
      onData(
        snap.docs.map(
          (d) => ({ id: d.id, ...(d.data() as Omit<QuickBooksExportDoc, "id">) })
        )
      );
    },
    (e) => onError?.(e as Error)
  );
}
